package tech.pronghorn.http.protocol

enum class HttpResponseHeader(val headerName: String,
                              val bytes: ByteArray) {
    AccessControlAllowOrigin("access-control-allow-origin", "access-control-allow-origin".toByteArray(Charsets.US_ASCII)),
    AcceptPatch("accept-patch", "accept-patch".toByteArray(Charsets.US_ASCII)),
    AcceptRanges("accept-ranges", "accept-ranges".toByteArray(Charsets.US_ASCII)),
    Age("age", "age".toByteArray(Charsets.US_ASCII)),
    Allow("allow", "allow".toByteArray(Charsets.US_ASCII)),
    AltSvc("alt-svc", "alt-svc".toByteArray(Charsets.US_ASCII)),
    CacheControl("cache-control", "cache-control".toByteArray(Charsets.US_ASCII)),
    Connection("connection", "connection".toByteArray(Charsets.US_ASCII)),
    ContentDisposition("content-disposition", "content-disposition".toByteArray(Charsets.US_ASCII)),
    ContentEncoding("content-encoding", "content-encoding".toByteArray(Charsets.US_ASCII)),
    ContentLanguage("content-language", "content-language".toByteArray(Charsets.US_ASCII)),
    ContentLength("content-length", "content-length".toByteArray(Charsets.US_ASCII)),
    ContentLocation("content-location", "content-location".toByteArray(Charsets.US_ASCII)),
    ContentMD5("content-md5", "content-md5".toByteArray(Charsets.US_ASCII)),
    ContentRange("content-range", "content-range".toByteArray(Charsets.US_ASCII)),
    ContentType("content-type", "content-type".toByteArray(Charsets.US_ASCII)),
    Date("date", "date".toByteArray(Charsets.US_ASCII)),
    ETag("etag", "etag".toByteArray(Charsets.US_ASCII)),
    Expires("expires", "expires".toByteArray(Charsets.US_ASCII)),
    LastModified("last-modified", "last-modified".toByteArray(Charsets.US_ASCII)),
    Link("link", "link".toByteArray(Charsets.US_ASCII)),
    Location("location", "location".toByteArray(Charsets.US_ASCII)),
    P3P("p3p", "p3p".toByteArray(Charsets.US_ASCII)),
    Pragma("pragma", "pragma".toByteArray(Charsets.US_ASCII)),
    ProxyAuthenticate("proxy-authenticate", "proxy-authenticate".toByteArray(Charsets.US_ASCII)),
    PublicKeyPins("public-key-pins", "public-key-pins".toByteArray(Charsets.US_ASCII)),
    Refresh("refresh", "refresh".toByteArray(Charsets.US_ASCII)),
    RetryAfter("retry-after", "retry-after".toByteArray(Charsets.US_ASCII)),
    Server("server", "server".toByteArray(Charsets.US_ASCII)),
    SetCookie("set-cookie", "set-cookie".toByteArray(Charsets.US_ASCII)),
    StrictTransportSecurity("strict-transport-security", "strict-transport-security".toByteArray(Charsets.US_ASCII)),
    Trailer("trailer", "trailer".toByteArray(Charsets.US_ASCII)),
    TransferEncoding("transfer-encoding", "transfer-encoding".toByteArray(Charsets.US_ASCII)),
    Tk("tk", "tk".toByteArray(Charsets.US_ASCII)),
    Upgrade("upgrade", "upgrade".toByteArray(Charsets.US_ASCII)),
    Vary("vary", "vary".toByteArray(Charsets.US_ASCII)),
    Via("via", "via".toByteArray(Charsets.US_ASCII)),
    Warning("warning", "warning".toByteArray(Charsets.US_ASCII)),
    WWWAuthenticate("www-authenticate", "www-authenticate".toByteArray(Charsets.US_ASCII)),
    XFrameOptions("x-frame-options", "x-frame-options".toByteArray(Charsets.US_ASCII))
}
